### ISSUE TITLE
Getting modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like f(...) is deprecated

### ISSUE THREAD

**Issue by ansuman13** [the-full-stack/ask-fsdl#77]
I am trying to do setup, following SETUP.MD file, getting an error while running `make document-store`

Error log seems to suggest modal Deprecation Error coming from `markdown.py`. 

Error Log:

```python
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 463, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 615, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/markdown.py", line 69, in to_documents
    text = get_text_from(markdown_url)
  File "/pkg/modal/functions.py", line 1401, in __call__
    deprecation_error(
  File "/pkg/modal/exception.py", line 120, in deprecation_error
    raise DeprecationError(f"Deprecated on {date(*deprecated_on)}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: Calling Modal functions like `f(...)` is deprecated. Use `f.local(...)` if you want to call the function in the same Python process. Use `f.remote(...)` if you want to call the function in a Modal container in the cloud
Stopping app - uncaught exception raised locally: TypeError("'UserCodeException' object is not iterable").
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/ansumansingh/Downloads/ask-fsdl-main/etl/markdown.py:45 in main                           │
│                                                                                                  │
│    44 │   documents = (                                                                          │
│ ❱  45 │   │   etl.shared.unchunk(  # each lecture creates multiple documents, so we flatten      │
│    46 │   │   │   to_documents.map(                                                              │
│                                                                                                  │
│ /Users/ansumansingh/Downloads/ask-fsdl-main/etl/shared.py:66 in unchunk                          │
│                                                                                                  │
│    65 │   """Recombines a list of lists into a single list."""                                   │
│ ❱  66 │   return [item for sublist in list_of_lists for item in sublist]                         │
│    67                                                                                            │
│                                                                                                  │
│ /Users/ansumansingh/Downloads/ask-fsdl-main/etl/shared.py:66 in <listcomp>                       │
│                                                                                                  │
│    65 │   """Recombines a list of lists into a single list."""                                   │
│ ❱  66 │   return [item for sublist in list_of_lists for item in sublist]                         │
│    67                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
...
```

**Comment by charlesfrye** [comment]
Thanks for the report, ansmuan!

This repo is no longer being actively maintained. But I believe you can resolve the issue by switching adding `.remote` to any call that triggers the deprecation warning.
